#!/usr/bin/env bash

# Check if a file name is provided as an argument
if [ $# -eq 0 ]; then
    echo "Error: No input file provided."
    exit 1
fi


# Count the occurrences of each month using awk
awk -F'\t' 'NR>1 { count[$6]++ } END { for (Month in count) print Month, count[Month] }' "$1"

