#!/usr/bin/env bash

# author_name: Kazi Md Imran ID: 23846485

if [[ $# -ne 1 ]]; then
   echo "Error: command is not complete. Expecting a data file to be passed."
   echo "Please recall the script!"
   exit 1
fi

# Remove any existing cleaned file
rm -f "$cleaned_file"

# Process the data file using Awk
awk -F'\t' '
{
    # Extract start date from range if present
    if ($4 ~ / - / || $4 ~ /- / || $4 ~ / -/ || $4 ~ /-/ ) {
   	 gsub(/ - /, "-", $4)
    	gsub(/- /, "-", $4)
    	gsub(/ -/, "-", $4)
	gsub(/-/, "-", $4)
    	split($4, dates, "-")
    	start_date = dates[1]
    } else {
    	start_date = $4
    }


    # Validate and transform start date
    if (start_date !~ /^[0-9]{1,2}\/[0-9]{1,2}\/[0-9]{2}$/ &&
        start_date !~ /^[0-9]{1,2}\/[0-9]{1,2}\/[0-9]{4}$/) {
        print "Invalid date:", NR
    } else {
        split(start_date, date, /[\/ -]/)
        month = date[1]
        day = date[2]
        year = date[3]
        if (length(year) == 2) {
            year = "20" year
        }
        if (month < 1 || month > 12 || day < 1 || day > 31 || year < 1) {
            print "Invalid date:", NR
        } else {
            start_date = sprintf("%02d/%02d/%s", month, day, year)
        }
    }

    # Write the cleaned data to the new file
    print start_date
}' "$1"


